<?xml version="1.0" encoding="utf-8"?><Database Name="Assigment" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Assigment;Integrated Security=True" SettingsObjectName="AssignmentDatabase.Properties.Settings" SettingsPropertyName="AssigmentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Username" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Account_Device" Member="Devices" ThisKey="Username" OtherKey="Owner" Type="Device" />
    </Type>
  </Table>
  <Table Name="dbo.Device" Member="Devices">
    <Type Name="Device">
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Account_Device" Member="Account" ThisKey="Owner" OtherKey="Username" Type="Account" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="DeviceType_Device" Member="DeviceType" ThisKey="Type" OtherKey="Code" Type="DeviceType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceType" Member="DeviceTypes">
    <Type Name="DeviceType">
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DeviceType_Device" Member="Devices" ThisKey="Code" OtherKey="Type" Type="Device" />
    </Type>
  </Table>
</Database>