CREATE TABLE DeviceType(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Code VARCHAR(10) NOT NULL UNIQUE,
	Description NVARCHAR(MAX),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Device(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Code VARCHAR(20) NOT NULL UNIQUE,
	Type INT NOT NULL FOREIGN KEY REFERENCES DeviceType(Id),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Account(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Username VARCHAR(100) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
)

INSERT INTO Account(Username, Name, Password) VALUES ('dinh', N'Định Trần', '123');
INSERT INTO Account(Username, Name, Password) VALUES ('hai', N'Hải Nguyễn', '123');
INSERT INTO Account(Username, Name, Password) VALUES ('khang', N'Khang', '123');