CREATE TABLE DeviceType(
	Code VARCHAR(10) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Description NVARCHAR(MAX),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Device(
	Code VARCHAR(20) PRIMARY KEY,
	Type INT NOT NULL FOREIGN KEY REFERENCES DeviceType(Code),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Account(
	Username VARCHAR(100) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
)

INSERT INTO Account(Username, Name, Password) VALUES ('dinh', N'Định Trần', '123');
INSERT INTO Account(Username, Name, Password) VALUES ('hai', N'Hải Nguyễn', '123');
INSERT INTO Account(Username, Name, Password) VALUES ('khang', N'Khang', '123');